### ISSUE TITLE
Tracking issue- tech debt

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/rules_scala#938]
This is a tracking issue for big tech debt we still have, this will contain links to tracking issues or concrete issues where applicable.
Full list can be tracked via this [search](https://github.com/bazelbuild/rules_scala/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Atech-debt+)

- [ ]  [Extract out common code](https://github.com/bazelbuild/rules_scala/issues/936)
- [ ]  Move from Label collection to manifest stamping
- [ ]  Move from "deps" patterns to defined toolchains
- [ ]  Move remaining rules to phases architecture
- [ ]  Align documentation with existing feature-set
